exclude:
  - node_modules
  - script

sass:
  style: :compressed

remote_theme: saadman-sakib/primer-dark


github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Jekyll Theme Primer Dark
description: Primer Dark is a Jekyll theme for GitHub Pages
